create table public.spring_session
(
    primary_id            char(36) not null
        constraint spring_session_pk
            primary key,
    session_id            char(36) not null,
    creation_time         bigint   not null,
    last_access_time      bigint   not null,
    max_inactive_interval integer  not null,
    expiry_time           bigint   not null,
    principal_name        varchar(100)
);

alter table public.spring_session
    owner to postgres;

create unique index spring_session_ix1
    on public.spring_session (session_id);

create index spring_session_ix2
    on public.spring_session (expiry_time);

create index spring_session_ix3
    on public.spring_session (principal_name);

create table public.spring_session_attributes
(
    session_primary_id char(36)     not null
        constraint spring_session_attributes_fk
            references public.spring_session
            on delete cascade,
    attribute_name     varchar(200) not null,
    attribute_bytes    bytea        not null,
    constraint spring_session_attributes_pk
        primary key (session_primary_id, attribute_name)
);

alter table public.spring_session_attributes
    owner to postgres;

create table public.users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password varchar(255) not null,
    role     varchar(255)
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    enabled  boolean      not null
);

alter table public.users
    owner to postgres;

create table public.verification_codes
(
    id          bigint       not null
        primary key,
    code        varchar(255) not null,
    expiry_date timestamp(6),
    user_id     bigint
        constraint ukbf0ofef2q09iwv2jg00aygy4q
            unique
        constraint fka4qo6nts1xd94owirq5evcpda
            references public.users
);

alter table public.verification_codes
    owner to postgres;

